POST http://localhost:3000/weathers
Content-Type: application/json

{
  "tempmin": 10,
  "tempmax": 20,
  "datetime": "2021-05-11",
  "description": "Test"
}

###
PUT http://localhost:3001/transactions/49
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJtZXJjaGFudCI6eyJpZCI6NTAsInNvY2lldHlOYW1lIjoiamtqc2RmaGtqIiwia2JpcyI6ImhramgiLCJjb25maXJtVXJsIjoia2oiLCJjYW5jZWxVcmwiOiJoayIsInRyYW5zYWN0aW9uU3VjY2Vzc1VybCI6ImpoayIsImN1cnJlbmN5IjoiamhramgiLCJzdGF0dXMiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjEtMDctMjJUMjE6MzA6NDcuMTc5WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMjJUMjE6MzE6MzAuNTI4WiJ9LCJ1c2VyIjp7ImlkIjo1MSwidXNlcm5hbWUiOiJtZXJjaGFudEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRDSzIwTmVFZVNaY0FjR0xYaTYuUXIuMFY3dmNSclR1a2t6RUYvZENOMUVuMHd2TjQ4RHFUVyIsImNyZWF0ZWRBdCI6IjIwMjEtMDctMjJUMjE6MzA6NDcuMTk3WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMjJUMjE6MzA6NDcuMTk3WiIsIk1lcmNoYW50SWQiOjUwfSwiaWF0IjoxNjI2OTg5NTE4LCJleHAiOjE2Mjk1ODE1MTh9.BAu1-lOkoUA9BdSdp4955O1ZM4X6ZW6ZvoLLQWtzzrVpwj2ssvAvPwEPdPYGmYy1VcKHGFvvz15ryk0_XNmDeg
Content-Type: application/json

{
  "status": "CANC"
}

###
GET http://localhost:3000/weathers?datetime=2020-03-04&startsWith[description]=Confinement

###
GET http://localhost:3000/users

###
POST http://localhost:3002/users
Content-Type: application/json

{
  "username": "test2@test.fr",
  "password": "test"
}

###
GET http://localhost:3000/users/1

###
PUT http://localhost:3000/users/5
Content-Type: application/json

{
  "password": "test4"
}

###
DELETE http://localhost:3000/users/1

###
GET http://localhost:3000/articles

###
PUT http://localhost:3000/articles/2
Content-Type: application/json

{
  "title": "foo"
}

###
POST http://localhost:3002/articles
Content-Type: application/json

{
  "title": "test",
  "content": "test content",
  "tags": [
    "test"
  ],
  "authorId": 1
}

###
POST http://localhost:3001/merchants
Content-Type: application/json

{
  "merchant": {
    "societyName": "Fanc",
    "kbis": "kbis test",
    "confirmUrl": "url confirm",
    "cancelUrl": "url cancel",
    "currency": "$",
    "clientToken": "token",
    "clientSecret": "secret"
  },
  "user": {
    "username": "lud11@lud.com",
    "password": "password"
  }
}

###
GET http://localhost:3000/merchants/1

###
GET http://localhost:3002/credentials

###
POST http://localhost:3002/credentials
Content-Type: application/json

{
  "clientToken": "token",
  "clientSecret": "secret",
  "merchantId": 2
}

###
POST http://localhost:3001/transactions
Content-Type: application/json

{
  "transaction": {
    "currency": "EUR",
    "totalPrice": "20000",
    "shippingAddress": "shippingAddress",
    "billingAddress": "billingAddress",
    "consumer": "consumer",
    "cart": "list"
  }
}

###
POST http://localhost:4000/
Content-Type: application/json

{
  "currency": "EUR",
  "totalPrice": "20000",
  "shippingAddress": "shippingAddress",
  "billingAddress": "billingAddress",
  "consumer": "consumer",
  "cart": "list"
}



###
DELETE http://localhost:3001/merchants/1


###
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "user@name.com",
  "password": "password"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "test2@test.fr",
  "password": "test"
}

###
GET http://localhost:3001/merchants
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6InRlc3QyQHRlc3QuZnIiLCJpYXQiOjE2MjY3MjU4ODQsImV4cCI6MTYyOTMxNzg4NH0.dYja09mcYgqOaBL33VKuF-NuTml8LyspP45dUAarOBj9WYY9Lz8Yf9ch9CG-33PZaENm0rj1u_nH6VApAgnwRQ


###
GET http://localhost:3001/transactions/merchant
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJtZXJjaGFudCI6eyJpZCI6NDksInNvY2lldHlOYW1lIjoiIiwia2JpcyI6IiIsImNvbmZpcm1VcmwiOiIiLCJjYW5jZWxVcmwiOiIiLCJ0cmFuc2FjdGlvblN1Y2Nlc3NVcmwiOiIiLCJjdXJyZW5jeSI6IiIsInN0YXR1cyI6ZmFsc2UsImNyZWF0ZWRBdCI6IjIwMjEtMDctMjJUMTg6MDQ6MTYuOTE1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMjJUMTg6MDQ6MTYuOTE1WiJ9LCJ1c2VyIjp7ImlkIjo1MCwidXNlcm5hbWUiOiJsdWRvQGx1ZG8uY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkc3VtV3VBejlUM1NzTUZ1VzdFUWl4ZWxlUUdZQ3BIMTNaeTNVN1A3aDBHMzR6NE83dlpsQkMiLCJjcmVhdGVkQXQiOiIyMDIxLTA3LTIyVDE4OjA0OjE2LjkzNVoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA3LTIyVDE4OjA0OjE2LjkzNVoiLCJNZXJjaGFudElkIjo0OX0sImlhdCI6MTYyNjk3Nzc5MCwiZXhwIjoxNjI5NTY5NzkwfQ.ufnmWN2xmAo0tqidyqb5R3nZx3nrzqCKRbh7DXSAWvjdTRA47FEPUaUzSmMqUXuxz1ywaTKoI2dyNzL-BdVzmw