POST http://localhost:3000/weathers
Content-Type: application/json

{"tempmin": 10, "tempmax": 20, "datetime": "2021-05-11", "description": "Test"}

###
PUT http://localhost:3000/weathers/609f9e79a3d9c4001fff91a7
Content-Type: application/json

{"tempmin": 3}

###
GET http://localhost:3000/weathers?datetime=2020-03-04&startsWith[description]=Confinement

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "test2@test.fr",
    "password": "test"
}

###
GET http://localhost:3000/users/1

###
PUT http://localhost:3000/users/5
Content-Type: application/json

{
    "password": "test4"
}

###
DELETE http://localhost:3000/users/1

###
GET http://localhost:3000/articles

###
PUT http://localhost:3000/articles/2
Content-Type: application/json

{
    "title": "foo"
}
###
POST http://localhost:3000/articles
Content-Type: application/json

{
    "title": "test",
    "content": "test content",
    "tags": ["test"],
    "authorId": 5
}

###
POST http://localhost:3000/merchants
Content-Type: application/json

{
    "societyName": "mcdo",
    "kbis": "kbis test",
    "confirmUrl": "url confirm",
    "cancelUrl": "url cancel",
    "currency": "$",
    "clientToken": "token",
    "clientSecret": "secret"
}

###
GET http://localhost:3000/merchants/1

###
POST http://localhost:3000/credentials
Content-Type: application/json

{
    "clientToken": "token",
    "clientSecret": "secret",
    "merchantId": 1
}

###
GET http://localhost:3000/credentials/1